--- #YAML:1.0
name:               XML-Compile-SOAP-Daemon
version:            3.03
abstract:           Daemon handling XML-SOAP
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Report:          0.9
    Test::More:           0.54
    Time::HiRes:          0
    XML::Compile:         1.24
    XML::Compile::Cache:  0.991
    XML::Compile::SOAP:   2.26
    XML::Compile::SOAP::WSA:  0.12
    XML::Compile::Tester:  0.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
